# Generated by Django 5.0.1 on 2026-03-04 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Mark as verified achievement'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='tags_text',
            field=models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'Python, Django, Backend')", max_length=500),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(help_text='FontAwesome icon class or emoji', max_length=100),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='issuer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Organization/Issuer'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='verification_url',
            field=models.URLField(blank=True, help_text='Link to verify the achievement'),
        ),
        migrations.AlterField(
            model_name='analyticssnapshot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
